### ISSUE TITLE
Request: Allow global constants to be controlled by a context manager

### ISSUE THREAD

**Issue by davidhassell** [NCAS-CMS/cfdm#100]
This so we can stop doing things like:

```python
>>> old = cfdm.log_level('DEBUG')
>>> <execute some code>
>>> cfdm.log_level(old)
```

and start doing things like:
```python
>>> with cfdm.log_level('DEBUG'):
...     <execute some code>
...
>>>
```

#### Implementation

The getter/setter function for each constant will have to return a `Constant` object, rather than the constant itself, which defines the `__enter__` and `__exit__` methods. The existing functions will be happy taking as input  either their current value type (e.g. `str`) or new `Constant` instance - i.e. all existing code will still work the same.

PR to follow.

**Comment by sadielbartholomew** [comment]
Ah, great idea! I imagine that shouldn't be too difficult to implement.
