### ISSUE TITLE
Container copy method implies deep copy behaviour

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cfdm#116]
Initial work towards doctesting has implied, and after further investigation I can confirm, that the `copy` method for the ABC `Container` (i.e. `cfdm.core.Container.copy`) that is [documented as being a deep copying operation](https://ncas-cms.github.io/cfdm/method/cfdm.core.Container.copy.html#cfdm.core.Container.copy) is in fact only displaying the behaviour of a shallow copy.

For example, note how the setting of a `_custom` dict component of `g` is also reflected in `f` when it is an item within a container, appearing to be a reference rather than a copy of that item, but not reflected in `f`f when a simple object:

```python
>>> # Setup
>>> import cfdm
>>> f = cfdm.core.abstract.container.Container()
>>> f._custom
{}
>>> f._custom['feature'] = ['f']
>>> f._custom
{'feature': ['f']}

# Apply the copy, expecting it to be deep
>>> g = f.copy()
>>> g._custom['feature'][0] = 'g'
>>> g._custom
{'feature': ['g']}

# ...but note how the change is also reflected in f:
>>> f._custom
{'feature': ['g']}

# ...though changing the top-level value for g does not influence f:
>>> g._custom['feature'] = 'gee whiz'
>>> g._custom
{'feature': 'gee whiz'}
>>> f._custom
{'feature': ['g']}
```

### Environment

```ipython
>>> cfdm.environment(paths=False)
Platform: Linux-4.15.0-54-generic-x86_64-with-glibc2.10
HDF5 library: 1.10.6
netcdf library: 4.7.4
Python: 3.8.5
netCDF4: 1.5.4
numpy: 1.19.4
cfdm.core: 1.8.8.1
cftime: 1.3.0
netcdf_flattener: 1.2.0
cfdm: 1.8.8.1
```

**Comment by sadielbartholomew** [comment]
@davidhassell I assume this is a bug and if so it would be good to discuss the best way to fix it. I have not investigated how far the shallowness of copy propagates throughout the codebase to inherited methods that do not override it, but this could be potentially a widespread issue?

Once I have prepared all of the doctest examples and included them in the main test suite run (currently I just have a `-d` option to run them separately), we will have explicit tests against this, since the docstring to the `_custom` method runs essentially the same code I have in my minimal example above:

https://github.com/NCAS-CMS/cfdm/blob/58d8fea23cb156bfa3a1c95e4751619e8f10d0fb/cfdm/core/abstract/container.py#L183-L207

**Comment by davidhassell** [comment]
Hi Sadie - not a bug, rather a performance feature! and the reason why the `_custom` attribute has the underscore. Deep copying this dictionary could be a major performance hit for anything that uses it (like cf-python), which is unknown to cfdm. If the custom dictionary contains any mutables (not including any which are considered copy-on-write), then it is up to the the parent class to copy those explicitly - either in its own `copy` method, or else inside an `if source is not None:` clause in its `__init__` method.

Currently, cfdm only uses `_custom` in `decorators.py` (https://github.com/NCAS-CMS/cfdm/blob/master/cfdm/decorators.py#L47-L53) - but I now think that we should _not_ use it or this purpose - i.e. reserve `_custom` for applications that subclass cfdm. The decorator use could instead easily be satisfied with a normal underscore attribute.

So I think that the `_custom` attribute docstring is correct, but it clearly needs a lot more explanation on the consequences of it. The closest we get is https://github.com/NCAS-CMS/cfdm/blob/master/cfdm/core/abstract/container.py#L31-L32, but that's not much use to developers. This needs to be described much more explicitly, particularly for those subclassing cfdm.

Thanks, David

**Comment by sadielbartholomew** [comment]
Hi @davidhassell, thanks for the clarification. That's good news if it is expected behaviour and therefore not a bug.

So if I understand correctly, it seems I have misunderstood between the deep copying of the objects and the dictionary attributes attached to them? That sounds very plausible given the complexities of copying, apologies!

However there are numerous doctests essentially equivalent to the example I raise in the opening comment that are still failing because they are expecting `f._custom` to be `{'feature': ['f']}` rather than `{'feature': ['g']}`. But you seem to be implying that docstring is correct, but also that the behaviour is as expected. So I am left unsure as to how to handle that docstring. Am I missing something still?

> Currently, cfdm only uses _custom in decorators.py (https://github.com/NCAS-CMS/cfdm/blob/master/cfdm/decorators.py#L47-L53) - but I now think that we should not use it or this purpose - i.e. reserve _custom for applications that subclass cfdm. The decorator use could instead easily be satisfied with a normal underscore attribute.

Fair point, that seems wise. Shall I make that change or would you prefer to? Is there a name you have in mind, otherwise perhaps `_cfdm_custom`, `_cfdm_internals` or something similar (that doesn't risk a nameclash and I would think better to have a more flexible name that, say, `_cfdm_decorators` in case we want to throw other things in that `dict`)?

**Comment by davidhassell** [comment]
Hi  - OK! I've now read the _custom docstring a bit more clearly. I think it is wrong. I seem to vaguely  remember that it _was_ deep copied at some dim and distant past whilst cfdm was being developed. Seeing as we explicitly only shallow copy it, it should probably just say something like:

```python
 """Customisable storage for additional attributes.

        .. versionadded:: (cfdm) 1.7.4

        **Examples:**

        >>> f = {{package}}.{{class}}()
        >>> f._custom
        {}
        >>> f._custom['feature'] = 1
        >>> g = f.copy()
        >>> g._custom
        {'feature':1}
        >>> del g._custom['feature']
        >>> g._custom
        {}
        >>> f._custom
        {'feature': 1}

        """
 ```
I'll think about some text to explain this in https://ncas-cms.github.io/cfdm/extensions.html

> Fair point, that seems wise. Shall I make that change or would you prefer to? Is there a name you have in mind, otherwise perhaps _cfdm_custom, _cfdm_internals or something similar (that doesn't risk a nameclash and I would think better to have a more flexible name that, say, _cfdm_decorators in case we want to throw other things in that dict)?

Do such things (currently just `_custom[INPLACE_ENABLED_PLACEHOLDER]`) need to be in a dict at all? Couldn't we just assign them as attributes in any case (e.g. https://github.com/NCAS-CMS/cfdm/blob/master/cfdm/decorators.py#L58-L61)?

**Comment by davidhassell** [comment]
> as I recall you suggested a key in _custom might be good.

I did indeed! Seemed like a good idea at the time ... 

If we say now that the rule for _custom is that it is only for external subclasses, perhaps that will clarify things for us and others? 

`_inplace_enabled` sounds good to me

**Comment by sadielbartholomew** [comment]
> If we say now that the rule for _custom is that it is only for external subclasses, perhaps that will clarify things for us and others?

Sounds good to me, yes.

> _inplace_enabled sounds good to me

Right-o, I'll do the conversion. Thanks.

**Comment by davidhassell** [comment]
See #117 for changes to the _custom docs

**Comment by sadielbartholomew** [comment]
Ah, excellent, thanks. That was quick! Are you waiting on the CI results or would you like me to review (seems simple enough that it might not be necessary, but can do if you wish)?

I've realised the doctest result output made it seem like there were numerous methods having that particular docstring example, but in fact it is only one case that appears multiple times across the methods in the various modules by inheritance. So this one fix will reduce the number of doctest failures raised significantly :)
