### ISSUE TITLE
Remove support for Python 3.6

### ISSUE THREAD

**Issue by davidhassell** [NCAS-CMS/cfdm#139]
Python 3.6 is already on security patches only - no bug fixes - with an end-of-life in December 2021 (https://endoflife.date/python)

There are already two work-arounds to support Python 3.6 relating to:

* `dict` not being ordered at 3.6
* no `re.Pattern` at 3.6
* 
Also:

* support for Python 3.6 has been dropped from `numpy` 1.20

I'm inclined to also drop support for 3.6 sooner than the end of the year.

What do you think?

**Comment by sadielbartholomew** [comment]
To me that timeline sounds sensible, thanks @davidhassell. As a further note that you may be aware of already, Dask dropped 3.6 support some months ago and when it becomes a dependency of ours for cf-python (hopefully well before the end of the year) we should ideally have dropped 3.6 too.

Shall we advertise this on some relevant NCAS Slack channels to check across a sub-sample of users and power users that nobody is aware of a reason someone might need to use cf-python or cfdm with 3.6 in the near future?

**Comment by davidhassell** [comment]
Hi @sadielbartholomew, Just to clarify, do you think waiting until December is sensible, or dropping 3.6 sooner? Thanks.

**Comment by sadielbartholomew** [comment]
Hi @davidhassell, sorry my previous response wasn't very clear; I do agree that sooner than this December is better, assuming that nobody comments here or on Slack etc. to indicate that dropping support for 3.6 would be problematic for them or for some group of users.
