### ISSUE TITLE
Remove test that prevents writing to a file that is about to be read

### ISSUE THREAD

**Issue by davidhassell** [NCAS-CMS/cfdm#192]
There is currently a reasonable test in `cfdm.write` to prevent writing to any file that needs to be read to realise a Field construct in memory: https://github.com/NCAS-CMS/cfdm/blob/v1.9.0.3/cfdm/read_write/netcdf/netcdfwrite.py#L4305-L4312

```python
        if fields and mode != "r":
            filename = os.path.abspath(filename)
            for f in fields:
                if filename in self.implementation.get_filenames(f):
                    raise ValueError(
                        "Can't write to a file that contains data "
                        f"that needs to be read: {filename}"
                    )
```

This is fine so long as any other implementation can provide a `get_filenames()` method with the same API.

However, it is becoming apparent that the future daskified version of cf-python can't reliably provide a `get_filenames()` method.

Therefore, I propose simply removing the above `if` clause from cfdm. It'd be nice to not have to do this, but I can't see a way around it. 

Removing this test would mean that cfdm (and cf-python) would, at least, become consistent with netCDF4-python, in that a file opened for reading can get trashed if subsequently opened for writing.

What do you think?

**Comment by davidhassell** [comment]
Thinking beyond this potential monkey patch, perhaps the cfdm `get_filenames()` methods could/should be deprecated. This would go along with the introduction of a new method that records the files that were read by `cfdm.read` ("get_original_filenames"?). This set of files would not ever change, even if subsequent construct manipulations implie a different set of files.

**Comment by davidhassell** [comment]
In the light of https://github.com/NCAS-CMS/cfdm/pull/216 that provide an `original_filenames` method, should we move to deprecate `get_filenames`?

**Comment by sadielbartholomew** [comment]
> should we move to deprecate get_filenames?

If it isn't (sufficiently) useful anymore, and there's definitely an argument for that, then let's go for it!

**Comment by davidhassell** [comment]
+1. I'll put in PR.
