### ISSUE TITLE
Online docs are for the wroing version

### ISSUE THREAD

**Issue by davidhassell** [NCAS-CMS/cfdm#208]
The on-line docs at https://ncas-cms.github.io/cfdm/ are for v1.9.0.4, but the files in the `docs` directory have been correctly updated to v1.10.0.0 (i.e. the current version).

Any ideas, @sadielbartholomew?

**Comment by sadielbartholomew** [comment]
Hmm, weird! My first thought was to check GitHub pages were functioning normally as [it seems they are](https://www.githubstatus.com/). I'll see if I can spot anything amiss and get back to you...

**Comment by sadielbartholomew** [comment]
Very strange, as I can second that everything seems correct on the codebase-side such that the v1.10.0.0 doc should be showing, all being well. You tried what I would have tried with [0c6f140](https://github.com/NCAS-CMS/cfdm/commit/0c6f140dc8229d41530d2b9f439f740a28645a33) to possibly bump GitHub Pages in case something was temporarily wrong there at the time of committing the new docs (though GitHub status indicates the last Pages incident was on 10th August, well before that). :thinking: 

Let me check the repo settings in case we can try something there to potentially trigger things...

**Comment by sadielbartholomew** [comment]
Aha! Got it - see 'Settings -> Pages' for the repo:

> Branch
Your GitHub Pages site is currently being built from the /docs folder in the 1.9.0.x branch. [Learn more](https://docs.github.com/articles/configuring-a-publishing-source-for-github-pages/).

So it isn't being built off of the `master` branch! I'll change that to `master`now and that should fix everything...

**Comment by sadielbartholomew** [comment]
And now we wait :watch: (should be 10 minutes or so in my experience given the number of pages to update)...

**Comment by sadielbartholomew** [comment]
Spoke too soon! It's already gone through and the shiny new 1.10.0.0 docs are rendering, so I'll close this.
