### ISSUE TITLE
Incorrect data assignment with some multiple list indices

### ISSUE THREAD

**Issue by davidhassell** [NCAS-CMS/cfdm#217]
When multiple list indices are provided to a data assignment (i.e. `Data.__setitem__`), the assignment works if all of the lists are strictly monotonically increasing, but only for some cases cases where they are not:

```python
>>> import cfdm
>>> d = cfdm.example_field(0).data
>>> d[[0, 3, 4], [1, 7, 6]].array 
array([[0.034, 0.029, 0.024],
       [0.059, 0.017, 0.009],
       [0.036, 0.013, 0.034]])
>>> d[[0, 3, 4], [1, 7, 6]] = -1       # all lists strictly monotonically increasing => OK
>>> d[[0, 3, 4], [1, 7, 6]].array 
array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])
```

```python
>>> import cfdm
>>> d = cfdm.example_field(0).data
>>> d[[0, 3, 4], [1, 6, 7]].array 
array([[0.034, 0.029, 0.024],
       [0.059, 0.017, 0.009],
       [0.036, 0.013, 0.034]])
>>> d[[0, 3, 4], [1, 7, 6]] = -1 
>>> d[[0, 3, 4], [1, 7, 6]].array        # one list not strictly monotonically increasing => OK (edited from "not OK"!)
array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])
```

```python
>>> d = cfdm.example_field(0).data
>>> d[[4, 3, 0], [7, 6, 1]] = -1
>>> d[[4, 3, 0], [7, 6, 1]].array       # both lists strictly monotonically decreasing => NOT OK
array([[ 0.013,  0.034,  0.036],
       [ 0.017,  0.009,  0.059],
       [ 0.029,  0.024, -1.   ]])
```
```python
>>> d = cfdm.example_field(0).data
>>> d[[4, 3, 0], [7, 6, 1]] = -1
>>> d[[4, 3, 0], [7, 6, 1]].array     # NOT OK
array([[ 0.013,  0.034,  0.036],
       [ 0.017,  0.009,  0.059],
       [ 0.029,  0.024, -1.   ]])
```
```python
>>> d = cfdm.example_field(0).data
>>> d[[0, 4, 3], [1, 7, 6]] = -1
>>> d[[0, 4, 3], [1, 7, 6]].array   # OK, though!
array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])
```

PR to follow (after cfdm has been transferred to `main`) (edit: https://github.com/davidhassell/cfdm/tree/data-setitem-multiple-list-indices-2, lest I forget)

```python
>>> cfdm.environment(paths=False)
Platform: Linux-5.14.0-1052-oem-x86_64-with-glibc2.31
HDF5 library: 1.12.1
netcdf library: 4.8.1
Python: 3.9.12
netCDF4: 1.6.0
numpy: 1.22.3
cfdm.core: 1.10.0.0
cftime: 1.6.1
netcdf_flattener: 1.2.0
cfdm: 1.10.0.0
```

**Comment by davidhassell** [comment]
Note - Whilst cfdm never said or trapped otherwise, this only ever really worked when all list indices (when there are at least two) were strictly monotonically increasing. This is because this code was back-ported from cf-python, which prior to v3.14 did insist on this (it was a LAMA thing). There is no need for this restriction in cf-python>=3.14, nor in cfdm.

**Comment by sadielbartholomew** [comment]
@davidhassell: whilst I am reviewing the associated PR, I just wanted to ask for clarity of describing the bug here: the first and second examples seems a bit confusing and contradictory to me, I am wondering if you wrote down quite what you meant? Namely, did you mean to put that the second example is 'OK' rather than 'NOT OK' since it seems to set the elements to `-1` as asked? And then the first example says is covers `all lists strictly monotonically increasing` but it doesn't do that? 

#### Example 1 (all lists strictly monotonically increasing)
```python
In [4]: d[[0, 3, 4], [1, 6, 7]].array
Out[4]: 
array([[0.034, 0.024, 0.029],
       [0.059, 0.009, 0.017],
       [0.036, 0.034, 0.013]])

In [5]: d[[0, 3, 4], [1, 6, 7]] = -1

In [6]: d[[0, 3, 4], [1, 6, 7]].array  # OK!
Out[6]: 
array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])
```

#### Example 2 (one list not strictly monotonically increasing, but in this case it works)
```python
In [7]: d = cfdm.example_field(0).data

In [8]: d[[0, 3, 4], [1, 7, 6]].array
Out[8]: 
array([[0.034, 0.029, 0.024],
       [0.059, 0.017, 0.009],
       [0.036, 0.013, 0.034]])

In [9]: d[[0, 3, 4], [1, 7, 6]] = -1

In [10]: d[[0, 3, 4], [1, 7, 6]].array  # OK!
Out[10]: 
array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])
```

**Comment by davidhassell** [comment]
Good spot! Your right, and I'll edit the original post.

**Comment by sadielbartholomew** [comment]
> Good spot! Your right, and I'll edit the original post.

Thanks for checking. It helps to know I am understanding correctly the issue I am meant to be reviewing on :slightly_smiling_face:
