### ISSUE TITLE
Dictionary view objects from methods to get constructs &/or keys

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cfdm#78]
The docstring description for the `items`, `keys` and `values` methods for `Constructs` instances implies they return `dict`s or `list`s, as they would have in Python 2, instead of the dict-like and list-like objects `dict_items`, `dict_keys` or `dict_values` that are returned in Python 3:

https://github.com/NCAS-CMS/cfdm/blob/1f34db734405c9ad6bb4cd9ce4d495a93cdcb3bd/cfdm/core/constructs.py#L754-L782

for example:

```pycon
>>> a = cfdm.example_field(0)
>>> a.constructs.items()
dict_items([('dimensioncoordinate0', <DimensionCoordinate: latitude(5) degrees_north>), ('dimensioncoordinate1', <DimensionCoordinate: longitude(8) degrees_east>), ('dimensioncoordinate2', <DimensionCoordinate: time(1) days since 2018-12-01 >), ('domainaxis0', <DomainAxis: size(5)>), ('domainaxis1', <DomainAxis: size(8)>), ('domainaxis2', <DomainAxis: size(1)>), ('cellmethod0', <CellMethod: area: mean>)])
>>> a.constructs.keys()
dict_keys(['domainaxis0', 'domainaxis1', 'domainaxis2', 'dimensioncoordinate0', 'dimensioncoordinate1', 'dimensioncoordinate2', 'cellmethod0'])
>>> a.constructs.values()
dict_values([<DimensionCoordinate: latitude(5) degrees_north>, <DimensionCoordinate: longitude(8) degrees_east>, <DimensionCoordinate: time(1) days since 2018-12-01 >, <DomainAxis: size(5)>, <DomainAxis: size(8)>, <DomainAxis: size(1)>, <CellMethod: area: mean>])
```

Given this is very likely a change resulting from the Python 2 to 3 port, I want to raise this to check what we want to return before fleshing out the return type in the documentation for further clarity. Do we want to return these view objects, or `dict`s or `list`s as applicable by converting via `dict()` or `list()` before returning?

I think the view objects are preferable because they are iterators so more efficient for iterations which seem to be by far the most common use case. But I see we also have an `__iter__` method available to use if iterators are required, so maybe we do want to return the standard Python structures instead(?):

https://github.com/NCAS-CMS/cfdm/blob/1f34db734405c9ad6bb4cd9ce4d495a93cdcb3bd/cfdm/core/constructs.py#L275-L283

Unless there is a requirement to return the alternative, I suggest we stick with returning the view objects but in the docstrings clarify that `dict` (`list`, as appropriate) can be called to convert from the view objects if a `dict` (`list`) is strictly required.

**Comment by davidhassell** [comment]
Hi @sadielbartholomew I agree. We should be returning the Python 3 view objects, and should smarten up the docstrings to make that clear.

(The returned objects are views of a dictionary copy of the `Constructs` object, rather than the Constructs object itself. I think this is not relevant, though, because you can't change the parent from the views anyway.)

**Comment by sadielbartholomew** [comment]
Thanks @davidhassell, in that case I will update the docstrings to make it clear what is being returned with an example of converting from the view objects afterwards, too.

There may be well be similar cases where we return view objects in cf-python, so I will check and also amend docstrings there if necessary.
