### ISSUE TITLE
Decorator to administer display keyword argument

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cfdm#96]
This is very low on the prioritisation list, but I've noticed there are several cases of logic to either return or print a constructed string keyword parameter depending on the value of a Boolean parameter display, essentially (in the most common case) the following:

```python
def <method name>(<args, other kwargs>, display=True):
    <...
    construct 'string' var
    ....>

    string = '\n'.join(string)

    if display:
        print(string)
    else:
        return string
```

and this would be a great candidate for logic to apply via a decorator. It should be fairly to implement such a decorator, too.

**Comment by davidhassell** [comment]
Sounds good to me.
